changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Новые возможности
      labels:
        - enhancement
    - title: Исправления
      labels:
        - bug
    - title: Документация
      labels:
        - documentation
    - title: Другие изменения
      labels:
        - '*'
