<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup><PackageReference Include="Npgsql" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../VideoGrabber.Platform.Contracts/VideoGrabber.Platform.Contracts.csproj" />
    <ProjectReference Include="../VideoGrabber.Platform.Core/VideoGrabber.Platform.Core.csproj" />
  </ItemGroup>
  <ItemGroup><EmbeddedResource Include="Migrations/*.sql" /></ItemGroup>
</Project>
